version: '3.8'

services:
  backend:
    build:
      context: ./backend
    container_name: backend
    ports:
      - "8080:8080"
    environment:
        SPRING_DATASOURCE_URL: jdbc:postgresql://database:5432/github_db
        SPRING_DATASOURCE_USERNAME: user_db
        SPRING_DATASOURCE_PASSWORD: 23_Usn{s,>pth_12
    depends_on:
      - database

  frontend:
    build:
      context: ./ui
    container_name: frontend
    ports:
      - "3000:80"
  database:
    image: postgres:17-alpine
    container_name: database
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: user_db
      POSTGRES_PASSWORD: 23_Usn{s,>pth_12
      POSTGRES_DB: github_db
    volumes:
      - database_data:/var/lib/postgresql/data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql:ro

volumes:
  database_data:
